
CREATE TABLE SportsComplex(
SportsComplex_PK INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
CL VARCHAR(50) NOT NULL,
CCOI VARCHAR(50) NOT NULL,
CTOA VARCHAR(50) NOT NULL
);

CREATE TABLE Event(
Event_PK INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
EPDate VARCHAR(50),
ED VARCHAR(50),
ENOfP VARCHAR(50),
ENOfO VARCHAR(50)
);

CREATE TABLE Holds(
Holds_PK INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
SportsComplex_PK VARCHAR(50) NOT NULL,
Event_PK VARCHAR(50) NOT NULL,
FOREIGN KEY (SportsComplex_PK) REFERENCES SportsComplex(SportsComplex_PK),
FOREIGN KEY (Event_PK) REFERENCES Event(Event_PK)
);

CREATE TABLE Official(
Offical_PK INT NOT NULL AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE Equipment(
Equipment_PK INT NOT NULL AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE Officiate(
Officiate_PK INT NOT NULL AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE Uses(
Uses_PK INT NOT NULL AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE ComplexType(
Complex_PK INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
NOfF VARCHAR(50),
Budget VARCHAR(50)
); 

CREATE TABLE OneSportComplex(
OneSportComplex INT NOT NULL AUTO_INCREMENT,
SportsComplex_PK VARCHAR(50) NOT NULL,
FOREIGN KEY (SportsComplex_PK) REFERENCES SportsComplex(SportsComplex_PK)
);

CREATE TABLE MultiSportComplex(
MultiSportComplex_PK INT NOT NULL AUTO_INCREMENT,
SportsComplex_PK VARCHAR(50) NOT NULL,
FOREIGN KEY (SportsComplex_PK) REFERENCES SportsComplex(SportsComplex_PK)
);


-- There should be 3 more tables (OneSportComplex, MultiSportComplex, Area) trying to figure out how to add them and what they should be--


