
CREATE TABLE SportsComplex(
SportsComplex_PK INT NOT NULL AUTO_INCREMENT,
CL VARCHAR(50) NOT NULL,
CCOI VARCHAR(50) NOT NULL,
CTOA VARCHAR(50) NOT NULL,
PRIMARY KEY(SportsComplex_PK)
);

CREATE TABLE Event(
Event_PK INT NOT NULL AUTO_INCREMENT,
EPDate VARCHAR(50),
ED VARCHAR(50),
ENOfP VARCHAR(50),
ENOfO VARCHAR(50),
PRIMARY KEY(Event_PK)
);

CREATE TABLE Holds(
Holds_PK INT NOT NULL AUTO_INCREMENT,
SportsComplex_PK INT NOT NULL,
Event_PK INT NOT NULL,
FOREIGN KEY (SportsComplex_PK) REFERENCES SportsComplex(SportsComplex_PK),
FOREIGN KEY (Event_PK) REFERENCES Event(Event_PK),
PRIMARY KEY(Holds_PK)
);

CREATE TABLE Official(
Official_PK INT NOT NULL AUTO_INCREMENT,
PRIMARY KEY(Official_PK)
);

CREATE TABLE Equipment(
Equipment_PK INT NOT NULL AUTO_INCREMENT,
PRIMARY KEY(Equipment_PK)
);

CREATE TABLE Officiate(
Officiate_PK INT NOT NULL AUTO_INCREMENT,
Event_PK INT NOT NULL,
FOREIGN KEY(Event_PK) REFERENCES Event(Event_PK),
PRIMARY KEY(Officiate_PK)
);

CREATE TABLE Uses(
Uses_PK INT NOT NULL AUTO_INCREMENT,
Event_PK INT NOT NULL,
FOREIGN KEY(Event_PK) REFERENCES Event(Event_PK),
PRIMARY KEY(Uses_PK)
);

CREATE TABLE ComplexType(
Complex_PK INT NOT NULL AUTO_INCREMENT,
NOfF VARCHAR(50),
Budget VARCHAR(50),
PRIMARY KEY(Complex_PK)
); 

CREATE TABLE OneSportComplex(
OneSportComplex_PK INT NOT NULL AUTO_INCREMENT,
SportsComplex_PK INT NOT NULL,
FOREIGN KEY (SportsComplex_PK) REFERENCES SportsComplex(SportsComplex_PK),
PRIMARY KEY(OneSportComplex_PK)
);

CREATE TABLE MultiSportComplex(
MultiSportComplex_PK INT NOT NULL AUTO_INCREMENT,
SportsComplex_PK INT NOT NULL,
FOREIGN KEY (SportsComplex_PK) REFERENCES SportsComplex(SportsComplex_PK),
PRIMARY KEY(MultiSportComplex_PK)
);


CREATE TABLE Area(
Area_PK INT NOT NULL AUTO_INCREMENT,
MultiSportComplex_PK INT NOT NULL,
LI VARCHAR(50),
FOREIGN KEY (MultiSportComplex_PK) REFERENCES MultiSportComplex(MultiSportComplex_PK),
PRIMARY KEY(Area_PK)
);



